<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mindheaven - Calendar</title>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>/css/counselor/calender.css">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar">
        <div class="nav-content">
            <div class="logo">
                <div class="logo-icon">M</div>
                Mindheaven
            </div>
            <div class="nav-icons">
                <div class="nav-icon">
                    🔔
                    <span class="badge">3</span>
                </div>
                <div class="nav-icon">
                    💬
                    <span class="badge">7</span>
                </div>
            </div>
        </div>
    </nav>

    <!-- Main Container -->
    <div class="main-container">
        <!-- Sidebar -->
        <div class="sidebar">
            <ul class="sidebar-menu">
                <!-- <li class="sidebar-item">📊 Dashboard</li>
                <li class="sidebar-item active">📅 Calendar</li> -->
                <li class="sidebar-item" ><a href="dashboard">📊 Dashboard</a></li>
                <li class="sidebar-item active"><a href="#" style="color: #2563eb;">📅 Calendar</a></li>
                <li class="sidebar-item"><a href="appointmentmgt">🗓️ Appointment Management</a></li>
                <li class="sidebar-item"><a href="sessionHistory">📋 Session History</a></li>
                <li class="sidebar-item"><a href="forum">💭 Forum</a></li>
                <li class="sidebar-item"><a href="resources">📚 Resource Hub</a></li>
                <li class="sidebar-item"><a href="counselor_profile">👤 Profile</a></li>
                <li class="sidebar-item">⚙️ Settings</li>
                <li class="sidebar-item logout-item"><a href="<?php echo BASE_URL; ?>/logout" onclick="return confirm('Are you sure you want to logout?')">🚪 Logout</a></li>
            </ul>
        </div>

        <!-- Main Content -->
        <div class="main-content">
            <!-- Today's Events -->
            <div class="todays-events">
                <div class="section-header">
                    <h2 class="section-title">📅 Today's Schedule</h2>
                </div>
                <div id="todaysEventsList">
                    <?php if (!empty($todaysEvents)): ?>
                        <?php foreach ($todaysEvents as $event): ?>
                            <div class="event-item">
                                <div class="event-details">
                                    <h4><?php echo htmlspecialchars($event->title); ?></h4>
                                    <p><?php echo htmlspecialchars($event->description); ?></p>
                                </div>
                                <div class="event-time"><?php echo date('g:i A', strtotime($event->event_time)); ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="event-item">
                            <div class="event-details">
                                <h4>No events scheduled</h4>
                                <p>You have a free day today!</p>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <!-- Calendar -->
            <div class="calendar-container">
                <div class="calendar-header">
                    <div class="calendar-nav">
                        <button class="nav-btn" onclick="previousMonth()">‹</button>
                        <div class="current-month" id="currentMonth">December 2024</div>
                        <button class="nav-btn" onclick="nextMonth()">›</button>
                    </div>
                    <button class="today-btn" onclick="goToToday()">Today</button>
                </div>
                
                <div class="calendar-grid">
                    <div class="weekdays">
                        <div class="weekday">Sun</div>
                        <div class="weekday">Mon</div>
                        <div class="weekday">Tue</div>
                        <div class="weekday">Wed</div>
                        <div class="weekday">Thu</div>
                        <div class="weekday">Fri</div>
                        <div class="weekday">Sat</div>
                    </div>
                    
                    <div class="days" id="calendarDays">
                        <!-- Calendar days will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add Event Button -->
    <button class="add-event-btn" onclick="showAddEventModal()">+</button>

    <!-- Add/Edit Event Modal -->
    <div id="eventModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="eventModalTitle">Add New Event</h3>
                <button class="close" onclick="closeModal('eventModal')">&times;</button>
            </div>
            <div class="modal-body">
                <form id="eventForm">
                    <input type="hidden" id="eventId" value="">
                    <div class="form-group">
                        <label class="form-label" for="eventTitle">Event Title</label>
                        <input type="text" id="eventTitle" class="form-input" placeholder="Enter event title" required>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label class="form-label" for="eventDate">Date</label>
                            <input type="date" id="eventDate" class="form-input" required>
                        </div>
                        <div class="form-group">
                            <label class="form-label" for="eventTime">Time</label>
                            <input type="time" id="eventTime" class="form-input" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="eventPriority">Priority</label>
                        <select id="eventPriority" class="form-input" required>
                            <option value="normal">Normal</option>
                            <option value="urgent">Urgent</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="eventDescription">Description</label>
                        <textarea id="eventDescription" class="form-textarea" placeholder="Add event details..."></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-actions">
                <button class="btn-secondary" onclick="closeModal('eventModal')">Cancel</button>
                <button class="btn-danger" id="deleteEventBtn" onclick="deleteEvent()" style="display: none;">Delete</button>
                <button class="btn-primary" onclick="saveEvent()" id="saveEventBtn">Save Event</button>
            </div>
        </div>
    </div>

    <!-- Day Events Modal -->
    <div id="dayEventsModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="dayEventsTitle">Events for Selected Day</h3>
                <button class="close" onclick="closeModal('dayEventsModal')">&times;</button>
            </div>
            <div class="modal-body">
                <div id="dayEventsList" class="day-events-list">
                    <!-- Day events will be populated here -->
                </div>
            </div>
            <div class="modal-actions">
                <button class="btn-secondary" onclick="closeModal('dayEventsModal')">Close</button>
                <button class="btn-primary" onclick="addEventForDay()">Add Event</button>
            </div>
        </div>
    </div>

    <script>
        // Pass PHP data to JavaScript
        const BASE = '<?php echo BASE_URL; ?>';
        const counselorId = <?php echo (int)$counselorId; ?>;
        const eventsFromPHP = <?php echo $eventsForJS ?: '{}'; ?>;
        
        console.log('BASE URL:', BASE);
        console.log('Counselor ID:', counselorId);
        
        
        // Add event listener as backup
        document.addEventListener('DOMContentLoaded', function() {
            const saveBtn = document.getElementById('saveEventBtn');
            const form = document.getElementById('eventForm');
            
            console.log('Save button found:', saveBtn);
            console.log('Form found:', form);
            
            if (saveBtn) {
                saveBtn.addEventListener('click', function(e) {
                    console.log('Save button clicked via event listener');
                    e.preventDefault();
                    saveEvent();
                });
            } else {
                console.error('Save button not found!');
            }
        });
    </script>
    <script src="<?php echo BASE_URL; ?>/js/counselor/calender.js?v=<?php echo time(); ?>"></script>
</body>
</html>